### ISSUE TITLE
30. Stacks

### ISSUE THREAD

**Issue by Tanushree-coder** [rahulsain/CPP-DSA#16]
I want to add few questions on stack (like balanced parenthesis, next greater element, stock span problem, celebrity problem and largest rectangular area in a histogram).
Should I make different PR for each question? @rahulsain 
#hacktober fest

**Comment by rahulsain** [comment]
> I want to add few questions on stack (like balanced parenthesis, next greater element, stock span problem, celebrity problem and largest rectangular area in a histogram). Should I make different PR for each question? @rahulsain #hacktober fest

No, make a single PR
